config/routes.rb
Rails.application.routes.draw do
  root to: 'store#index'
  resources :books
  resources :authors
  resources :categories
  resources :users
  resources :sessions, only: [:new, :create]

  get 'cart/add/:book_id', to: 'cart#add_book', as: 'add_to_cart'
  patch 'cart/update-quantity', to: 'cart#update_quantity', as: 'update_cart_quantity'
  get 'cart/show', to: 'cart#show', as: 'view_cart'

  delete 'logout', to: 'sessions#destroy'
  get 'store/index', as: 'store_index'

  get 'settings', to: 'settings#index'
  get 'orders/address', to: 'orders#address', as: 'add_order_address'
  get 'orders/index', to: 'orders#index', as: 'orders'
  post 'orders/address', to: 'orders#save_address', as: 'save_order_address'
  get 'orders/checkout', to: 'orders#checkout', as: 'orders_checkout'
  get 'orders/:id', to: 'orders#show', as: 'order'
  post 'orders/finish', to: 'orders#finish_checkout', as: 'finish_checkout'
  get '/admin', to: 'admin_session#new'
  post '/admin', to: 'admin_session#create', as: 'admin_session'
  get '/admin/orders', to: 'admin#orders', as: 'admin_orders'
  get '/admin/users', to: 'admin#users', as: 'admin_users'
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def orders
  end

  def users
  end
end

app/controllers/admin_session_controller.rb
class AdminSessionController < ApplicationController
  def new
  end

  def create
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :user_presenter
  helper_method :categories

  def user_presenter
    @user_presenter ||= UserPresenter.new(session_service: session_service)
  end

  def session_service
    @session_service ||= SessionService.new(session: session)
  end

  def cart_service
    @cart_service ||= CartService.new(session: session)
  end

  def categories
    @categories ||= CategoryRepository.all
  end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def index
    @authors = AuthorRepository.all
  end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def show
    @cart = CartPresenter.new(cart: cart_service.cart)
  end

  def update_quantity
    UpdateCartQuantity.call(cart: cart_service, params: update_cart_params)
    redirect_to view_cart_path, notice: 'Quantities updated'
  end

  def add_book
    AddToCart.call(cart: cart_service, params: params)
    redirect_to view_cart_path, notice: 'Added book to cart'
  end

  private

  def update_cart_params
    params.require(:line_item).permit(:id, :quantity)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def address
    order
    @countries = CountryRepository.all
  end

  def save_address
    result = SaveAddress.call(session: session_service,
                              cart: cart_service,
                              params: save_address_params)
    if result.success?
      redirect_to orders_checkout_path
    else
      redirect_to add_order_address_path, alert: "Error saving order. #{result.errors}"
    end
  end

  def checkout
    @order = CalculateOrderCosts.call(order: order)
  end

  def finish_checkout
    @order.confirmed!
    @order.update_attribute(:user_id, @current_user.id)
    @order.update_book_sold_count
    OrderMailer.new_order(@order).deliver_now
    OrderMailer.new_customer_order(@order).deliver_now
    session.delete :order_id
    session.delete :cart_id
    redirect_to root_path, notice: 'Order sent successfully'
  end

  private

  def order
    @order ||= find_existing_order || Order.new
    @order
  end

  def find_existing_order
    OrderRepository.find(session[:order_id])
  end

  def save_address_params
    params.require(:order).permit(:name, :address, :country_id, :payment_type)
  end
end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  def index
    @new_books = book_service.newest(limit: 10)
    @best_books = book_service.bestselling(limit: 10)
  end

  private

  def book_service
    @book_service ||= BookService.new
  end
end

app/views/application/_book_item.html.erb
<ul class="thumbnail-list">
  <% books.each do |book| %>
    <li>
      <a href="<%= book_path(book.id) %>">
        <%= raw "<img src='data:image/png;base64,#{book.cover}' class=\"book-image\">" %>
      </a>
      <%= link_to(book.name, book.book, class: 'block book-title', title: book.name) %>
      <%= link_to(book.author.name, book.author, class: 'block') %>
      <div class="book-price"><%= book.price %> €</div>
      <a type="button" class="btn btn-default navbar-btn" href="<%= add_to_cart_path(book.id) %>">Add to Cart</a>
    </li>
  <% end %>
</ul>

app/views/application/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <div class="row">
      <div class="col-md-3 col-sm-3">
        <ul class="nav navbar-nav">
          <li>
            <a class="navbar-brand" href="<%= root_url %>">
              <%= image_tag 'logo.png', id: 'logo' %>
              <span>book-a-book</span>
            </a>
          </li>
        </ul>
      </div>
      <div class="col-md-6 col-sm-6">
        <ul class="nav navbar-nav">
          <li>
            <div class="input-group">
              <input type="hidden" name="search_param" value="all" id="search_param">
              <input type="text" class="form-control" name="x" placeholder="Search">
              <span class="input-group-btn">
                <button class="btn btn-default" type="button">
                  <span class="glyphicon glyphicon-search"></span>
                </button>
              </span>
            </div>
          </li>
        </ul>
      </div>
      <div class="col-md-3 col-sm-3">
        <ul class="nav navbar-nav pull-right navbar-right">
          <%= user_presenter.my_account(view_context: self) %>
        </ul>
      </div>
    </div>
  </div>
</nav>

app/views/application/_header_admin_account.html.erb
<li><%= link_to 'Orders', admin_orders_path %></li>
<li><%= link_to 'Users', admin_users_path %></li>

app/views/application/_header_login.html.erb
<li><%= link_to "Log in", new_session_path %></li>
<li><%= link_to 'Register', new_user_path %></li>

app/views/application/_header_user_account.html.erb
<li><%= link_to 'Cart', view_cart_path %></li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
    Account <b class="caret"></b>
  </a>
  <ul class="dropdown-menu">
    <li><%= link_to "Settings", settings_path %></li>
    <li><%= link_to "Orders", orders_path %></li>
    <li class="divider"></li>
    <li>
      <%= link_to "Log out", logout_path, method: "delete" %>
    </li>
  </ul>
</li>

app/views/application/_sidebar.html.erb
<ul class="list-group list-unstyled">
  <% categories.each do |category| %>
    <li class="">
      <%= link_to(category.name, category_path(category.id), class: 'no-color list-group-item') %>
    </li>
  <% end %>
</ul>

app/views/authors/index.html.erb
<ul>
<% @authors.each do |author| %>
  <li><%= author.name %></li>
<% end %>
</ul>

app/views/cart/show.html.erb
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>

<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

<% if @cart.empty? %>
  <h3>Your cart is empty.</h3>
<% else%>
  <h3>Your cart contains <%= @cart.count %> items: </h3>
  <div class="col-md-8">

  <%= form_for @cart.cart, url: update_cart_quantity_path do |f| %>
    <table class="table table-striped">
      <tr>
        <th>#</th>
        <th>Name</th>
        <th>Quantity</th>
        <th>Price</th>
        <th class="text-right">Total</th>
      </tr>
      <% @cart.line_items.each_with_index do |item, index| %>
        <tr>
          <td><%= index + 1 %></td>
          <td><%= @cart.book_name(item) %></td>
          <td>
            <%= f.fields_for :line_items, item do |item_form| %>
              <%= item_form.hidden_field :id %>
              <%= item_form.number_field :quantity, style: 'width: 35px' %>
            <% end %>
          </td>
          <td><%= item.price %>€</td>
          <td class="text-right"><%= item.quantity * item.price %>€</td>
        </tr>
      <% end %>
      <tr>
        <td colspan="5"></td>
      </tr>
      <tr>
        <td colspan="5" class="text-right">
          <%= f.submit 'Update Cart', class: 'btn btn-default' %>
        </td>
      </tr>
    </table>
  <% end %>
  </div>
  <div class="col-md-4 text-right checkout-side">
    <div>
      <h3>Order Total: <%= @cart.total %>€</h3>
    </div>
    <a href="<%= add_order_address_path %>" class="btn btn-default">Go to Checkout</a>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookbookTdd</title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'header' %>
    <div style="padding-top: 15px;" class="container main-container">
      <div class="row">
        <div class="col-sm-2 col-md-2">
          <%= render 'sidebar' %>
        </div>
        <div class="col-sm-10 col-md-10">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/orders/address.html.erb
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>
<div class="col-md-6 col-sm-6">
  <%= form_for @order, url: save_order_address_path, method: :post do |f| %>
  <fieldset>
    <legend>Address</legend>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :address %>
      <%= f.text_field :address, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :country_id %>
      <%= f.collection_select(:country_id, @countries, :id, :name, { prompt: true }, { class: 'form-control' }) %>
    </div>
  </fieldset>
  <fieldset>
    <legend>Payment method</legend>
    <div class="form-group">
      <%= f.label :payment_type %>
      <%= f.select :payment_type, Order.payment_types.keys, { prompt: true }, { class: 'form-control' } %>
    </div>
  </fieldset>
  <div class="form-group">
    <%= f.submit 'Continue', class: 'btn btn-default' %>
  </div>
  <% end %>
</div>
<div class="col-md-4 col-sm-4 col-md-offset-2 col-sm-offset-2">
  <h4>Order Summary</h4>
  <table class="table">
    <% @cart.line_items.each_with_index do |item, index| %>
      <tr class="info">
        <td>
          <%= link_to(item.book.name, book_path(item.book)) %>
        </td>
        <td>
          x
        </td>
        <td>
          <%= item.quantity %>
        </td>
      </tr>
    <% end %>
  </table>
</div>

app/views/orders/checkout.html.erb
<h3>Finish your order</h3>

<div class="col-sm-9 col-md-9">
  <table class="table">
    <tr>
      <td>
        Total
      </td>
      <td>
        <%= number_to_currency(@order.total, unit: '€', precision: 2) %>
      </td>
    </tr>
    <tr>
      <td>Tax for <%= @order.country.name %></td>
      <td><%= number_to_currency(@order.tax, unit: '€', precision: 2) %></td>
    </tr>
    <tr>
      <td>Shipping cost</td>
      <td><%= number_to_currency(@order.shipping_cost, unit: '€', precision: 2) %></td>
    </tr>
    <tr>
      <td>Grand Total</td>
      <td><%= number_to_currency(@order.total_with_tax + @order.shipping_cost, unit: '€', precision: 2) %></td>
    </tr>
    <tr>
      <td colspan="2">
        <%= link_to 'Finish order', finish_checkout_path, method: :post, class: 'btn btn-success' %>
      </td>
    </tr>
  </table>
</div>

<div class="col-sm-3 col-md-3">
  <% if @order.shipping_cost > 0 %>
    <p class="alert alert-warning text-center">
    Add <%= number_to_currency(Order::AMOUNT_FOR_FREE_SHIPPING - @order.total_with_tax, unit: '€', precision: 2) %> more for free shipping
    </p>
  <% end %>
</div>

app/views/orders/index.html.erb
<% if @orders.empty? %>
  You don't have any previous orders
<% else %>
  <table class="table table-bordered">
    <tr>
      <th>Order id</th>
      <th>Order date</th>
      <th>Number of items</th>
      <th>Total</th>
      <th>Action</th>
    </tr>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.id %>
        <td>
          <%= order.created_at %>
        </td>
        <td><%= order.item_count %></td>
        <td><%= number_to_currency(order.total_with_tax + order.shipping_cost, unit: '€', precision: 2) %></td>
        <td><%= link_to('View details', order_path(order)) %>
      </tr>
    <% end %>
  </table>
<% end %>

app/views/orders/show.html.erb
<h3>Order details</h3>
<h4>Items in the order:</h4>

<table class="table table-bordered">
  <tr>
    <th>Book title</th>
    <th>Quantity</th>
    <th>Price</th>
  </tr>
  <% @order.line_items.each do |item| %>
    <tr>
      <td><%= link_to(item.book.name, book_path(item.book.id)) %></td>
    <td><%= item.quantity %></td>
    <td><%= number_to_currency(item.price, unit: '€', precision: 2) %></td>
    </tr>
  <% end %>
</table>

<h4>Items in the order:</h4>
<table class="table-bordered table">
  <tr>
    <td>Shipping cost</td>
    <td><%= number_to_currency(@order.shipping_cost, unit: '€', precision: 2) %><br></td>
  </tr>
  <tr>
    <td>Payed with</td>
    <td><%= @order.payment_type %></td>
  </tr>
  <tr>
    <td>Tax</td>
    <td><%= number_to_currency(@order.tax, unit: '€', precision: 2) %></td>
  </tr>
</table>
<br><br><br>
<%= link_to('Back to orders', orders_path) %>

app/views/store/index.html.erb
<% if notice %>
<p class="alert alert-success"><%= notice %></p>
<% end %>

<h3>New releases</h3>
<div class="new-releases">
  <%= render 'book_item', books: @new_books %>
</div>

<h3>Bestsellers</h3>
<div class="best-sellers">
  <%= render 'book_item', books: @best_books %>
</div>